name: run-bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas openpyxl reportlab python-telegram-bot==13.15

      - name: Show Files
        run: ls -R

      - name: Run Bot
        run: |
          echo "Starting bot..."
          python bot.py
